# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_logistics_application', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applications',
            new_name='Application',
        ),
        migrations.RenameModel(
            old_name='OpenClasses',
            new_name='OpenClass',
        ),
    ]
