# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_logistics_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationfields',
            name='field_text',
            field=models.CharField(default='asdf', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationfields',
            name='from_student',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='gpa',
            field=models.FloatField(choices=[(4.0, '4.0'), (3.9, '3.9'), (3.8, '3.8'), (3.7, '3.7'), (3.6, '3.6'), (3.5, '3.5'), (3.4, '3.4'), (3.3, '3.3'), (3.2, '3.2'), (3.1, '3.1'), (3.0, '3.0'), (-1, '< 3.0')]),
        ),
        migrations.AlterField(
            model_name='students',
            name='teaching_experience',
            field=models.CharField(max_length=400),
        ),
    ]
