# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_logistics_application', '0002_auto_20161017_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statustext',
            name='status_text',
            field=models.CharField(max_length=30),
        ),
    ]
