# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_logistics_application', '0003_auto_20161017_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='statustext',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statustext',
            name='status_type',
            field=models.IntegerField(),
        ),
    ]
