# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import ta_logistics_application.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ta_logistics_application', '0005_auto_20161017_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassApplicants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('application_status_id', models.IntegerField()),
                ('hiring_status_id', models.IntegerField()),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('personal_statement', models.CharField(max_length=400)),
                ('class_grade', models.CharField(max_length=2)),
                ('optional_fields', models.CharField(default='', max_length=5000, validators=[ta_logistics_application.validators.validate_optional_field_json])),
            ],
        ),
        migrations.DeleteModel(
            name='ApplicationStatus',
        ),
    ]
