# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 20:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('ta_logistics_application', '0006_auto_20161017_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationfields',
            name='data_type',
            field=models.CharField(choices=[('TEXT', 'Text String'), ('INT', 'Integer Number'), ('REAL', 'Decimal Number')], max_length=6),
        ),
        migrations.AlterField(
            model_name='applicationfields',
            name='max_length',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(400)]),
        ),
        migrations.AlterField(
            model_name='classapplicants',
            name='class_grade',
            field=models.CharField(choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('< C-', '< C-')], max_length=4),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='classes',
            name='selected_optional_field_ids',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
