# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_logistics_application', '0007_auto_20161019_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
