# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_logistics_application', '0002_auto_20161008_0740'),
        ('ta_logistics_application', '0008_classes_is_active'),
    ]

    operations = [
    ]
