# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_logistics_application', '0008_classes_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubit_name', models.CharField(max_length=30)),
                ('person_number', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('semester', models.CharField(max_length=30)),
                ('class_id', models.CharField(max_length=30)),
                ('application_status', models.CharField(max_length=30)),
            ],
        ),
    ]
