# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_logistics_application', '0009_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='id',
        ),
        migrations.AlterField(
            model_name='status',
            name='ubit_name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
