# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_logistics_application', '0009_auto_20161027_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationfields',
            name='data_type',
            field=models.CharField(choices=[('TEXT', 'Text String'), ('INT', 'Integer Number'), ('REAL', 'Decimal Number'), ('CMFT', 'Programming Langage Comfort Level')], max_length=6),
        ),
    ]
