# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_logistics_application', '0010_auto_20161106_1418'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationFields',
        ),
    ]
