# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_logistics_application', '0010_auto_20161108_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='class_name',
            field=models.CharField(default='ok', max_length=30),
            preserve_default=False,
        ),
    ]
