# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 14:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import ta_logistics_application.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ta_logistics_application', '0011_delete_applicationfields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=30)),
                ('field_text', models.CharField(max_length=30)),
                ('is_default', models.BooleanField()),
                ('from_student', models.BooleanField()),
                ('data_type', models.CharField(choices=[('TEXT', 'Text String'), ('INT', 'Integer Number'), ('REAL', 'Decimal Number'), ('CMFT', 'Programming Langage Comfort Level')], max_length=6)),
                ('max_length', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(400)])),
                ('select_options', models.CharField(default='', max_length=500, validators=[ta_logistics_application.validators.validate_optional_field_json])),
                ('allow_multiple', models.BooleanField(default=False)),
            ],
        ),
    ]
