# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_logistics_application', '0013_auto_20161106_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationfields',
            name='allow_multiple',
        ),
    ]
