# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_logistics_application', '0013_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='status',
            name='ubit_name',
            field=models.CharField(max_length=30),
        ),
    ]
