# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_logistics_application', '0014_remove_applicationfields_allow_multiple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationfields',
            name='from_student',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='applicationfields',
            name='is_default',
            field=models.BooleanField(default=0),
        ),
    ]
