# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 18:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_logistics_application', '0015_auto_20161106_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationfields',
            name='data_type',
            field=models.CharField(choices=[('TEXT', 'Text String'), ('INT', 'Integer Number'), ('REAL', 'Decimal Number'), ('CMFT', 'Programming Language Comfort Level')], max_length=6),
        ),
        migrations.AlterField(
            model_name='applicationfields',
            name='max_length',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(400)]),
        ),
        migrations.AlterField(
            model_name='applicationfields',
            name='select_options',
            field=models.CharField(default='', max_length=500),
        ),
    ]
