# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 23:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_logistics_application', '0016_auto_20161106_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationfields',
            name='max_length',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400)]),
        ),
    ]
