# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_logistics_application', '0014_auto_20161108_1749'),
        ('ta_logistics_application', '0017_auto_20161106_2357'),
    ]

    operations = [
    ]
