# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-12 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_logistics_application', '0017_auto_20161106_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_number', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('semester', models.CharField(max_length=30)),
                ('class_id', models.CharField(max_length=30)),
                ('class_name', models.CharField(max_length=30)),
                ('application_status', models.CharField(max_length=30)),
                ('ubit_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='professors',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
