# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_logistics_application', '0018_auto_20161112_1818'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='classapplicants',
            name='is_registered_for_credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classapplicants',
            name='number_credits',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=0),
        ),
    ]
