# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 06:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_logistics_application', '0009_merge_20161029_1104'),
        ('ta_logistics_application', '0018_auto_20161112_1818'),
    ]

    operations = [
    ]
