# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_logistics_application', '0020_auto_20161120_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classapplicants',
            old_name='given_offer',
            new_name='pending_offer',
        ),
    ]
