# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-10 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_logistics_application', '0021_auto_20161120_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professors',
            name='ubit_name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='person_number',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='ubit_name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
