# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-11 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_logistics_application', '0022_auto_20161210_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payrollinfo',
            old_name='been_ub_employee',
            new_name='been_on_ub_payroll',
        ),
        migrations.RenameField(
            model_name='payrollinfo',
            old_name='other_on_campus_job',
            new_name='working_on_campus_while_being_ta',
        ),
        migrations.AddField(
            model_name='classapplicants',
            name='payroll_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payrollinfo',
            name='class_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollinfo',
            name='student_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payrollinfo',
            name='fall_and_spring',
            field=models.TextField(choices=[('Spring', 'Spring'), ('Fall', 'Fall'), ('Both', 'Both')], default=0),
        ),
    ]
