# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-11 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_logistics_application', '0024_remove_classapplicants_pending_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classapplicants',
            name='payroll_ready',
        ),
        migrations.AddField(
            model_name='payrollinfo',
            name='is_on_payroll',
            field=models.BooleanField(default=False),
        ),
    ]
